### PR TITLE
Destination fix

### LINKED ISSUE #16: [Bug] Dragging a function onto argument works inconsistently
Chrome/OSX:
1) Open wescheme example, and add a new expression (+ 1 2 3 4)
2) Drag the function on top of 4

EXPECTED: 1 becomes the function, whose arguments are 2 3 +
RESULT: No-op

The same happens if you try to replace the 3, BUT replacing the 1 and 2 works perfectly

### PR DESCRIPTION
**Pull request by schanzer**
Grabbing the ID from event.target is much more reliable. Use that to reconstruct the destination location, instead of relying on the node we're being passed.

Fixes #16

### CODE REVIEW

File: src/blocks.js [hunk 1]
```diff
@@ -479,95 +479,77 @@ export default class CodeMirrorBlocks {
...
-    let destination = getLocationFromEl(event.target);
-
-    if (!destination) {
-      // event.target probably isn't a drop target, so just get the location from the event
-      destination = this.cm.coordsChar({left:event.pageX, top:event.pageY});
-      if (destination.outside) {
-        sourceNodeText = '\n' + sourceNodeText;
-      }
+    // look up the destination information: ID, Node, destFrom and destTo
+    let destinationId   = event.target.id.substring(11);            // remove "blocks-node-" from the front
```
Comment (pcardune) [inline src/blocks.js]: You should use `this.findNodeFromEl(event.target)` for this. It encapsulates the substring part in a slightly better way :)

File: src/blocks.js [hunk 2]
```diff
@@ -479,95 +479,77 @@ export default class CodeMirrorBlocks {
...
-        this.cm.replaceRange(sourceNodeText, destination);
+    // then try to move the #f over one space. It should be a no-op.  
+    if (sourceNode) {
+      if( (this.poscmp(destFrom, sourceNode.from) > -1) && 
+          (this.poscmp(destTo,   sourceNode.to  ) <  1)) {
+        // destination range falls within the source range, so this should be a no-op.
+        return;
       }
+    } else {
+      // if we're inserting/replacing from outsider the editor, just do it and return
```
Comment (pcardune) [inline src/blocks.js]: s/outsider/outside

File: src/blocks.js [hunk 3]
```diff
@@ -174,9 +174,9 @@ export default class CodeMirrorBlocks {
     }
   }
 
-  markText(from, to, options) {
-    function poscmp(a, b) { return a.line - b.line || a.ch - b.ch; }
+  poscmp(a, b) { return a.line - b.line || a.ch - b.ch; }
```
Comment (pcardune) [inline src/blocks.js]: `poscmp` can probably be a module function instead of an instance method. Also add a doc comment about what the behavior is. I always get so confused with comparator functions and I can never remember what negative or positive return values actually mean.

**Comment by pcardune** [comment]
Just some minor code stuff. Since this is a bug fix, it would be great if you could write a unit test that captures what the bug was so that it doesn't get reintroduced in future refactoring.

File: src/blocks.js (hunk 1 above)
Comment (schanzer) [inline src/blocks.js]: This may be the bug I alluded to, because doing this has different behavior. For the test on https://github.com/bootstrapworld/codemirror-blocks/blob/master/spec/blocks-test.js#L534-L541 , the nodeId is null using the `substring` method but not using `findNodeFromEl`. 

I think this is because `findNearestNodeEl` will produce the _parent_ of a whitespace node, instead of the null value that would otherwise tell `dropOntoNode` to use `getLocationFromEl`.

If you're certain the semantics of `findNodeFromEl` are correct, then we need a different function for this purpose. But maybe those semantics aren't what we want?

Comment (pcardune) [inline src/blocks.js]: Ah I see. I think the semantics of `findNearestNodeEl` are correct. But you should at least extract out the common code for going from element &rarr; AST node based on the element id.

**Comment by schanzer** [comment]
Refactored, fixed comments, and added tests. Passing the token back to you to merge or suggest additional changes.

**Comment by pcardune** [comment]
looks good. Just rebase onto master and merge away.
